default:
  image: u_verilator:latest

stages:
  - initialize

initialize:
  stage: initialize
  script:
    - make repository_init
    - which verilator
    - verilator --version
    artifacts:
    expire_in: "30 mins"
    paths:
      - .bender/git/checkouts/
      - vendor_ips/
