name: verilator

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: veryl-lang/setup-verilator@v1
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: check environment
      run: |
        verilator --version
        python --version
        make verilator-generate-bindings
