name: verilator

on:
  workflow_dispatch:

jobs:
  test-verilator:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: veryl-lang/setup-verilator@v1
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: check environment
      run: |
        curl --proto '=https' --tlsv1.2 https://pulp-platform.github.io/bender/init -sSf | sh
        verilator --version
        python --version
        bender --version
        python -m pip install --requirement verification/verilator/requirements.txt
        make verilator-generate-bindings
        make verilator-inject-bindings
        make verilator-generate-model
        make verilator-run
